apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: jboss/keycloak:15.0.1
          env:
            - name: KEYCLOAK_USER
              value: admin
            - name: KEYCLOAK_PASSWORD
              value: admin 
            - name: KEYCLOAK_IMPORT
              value: /opt/jboss/keycloak/imports/realm-config.json
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 500m
              memory: 400Mi
          volumeMounts:
            - name: keycloak-config-volume
              mountPath: /opt/jboss/keycloak/imports/
      volumes:
      - name: keycloak-config-volume
        configMap:
          name: keycloak

---

apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  type: ClusterIP
  selector:
    app: keycloak
  ports:
  - protocol: TCP
    port: 9080
    targetPort: 8080
