apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-subscription
  labels:
    db: postgres-subscription
spec:
  selector:
    matchLabels:
      db: postgres-subscription
  template:
    metadata:
      labels:
        db: postgres-subscription
    spec:
      containers:
        - name: postgres-subscription
          image: postgres:13.4
          env:
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password 
            - name: POSTGRES_DB
              value: companydb_subscription
          resources:
            requests:
              cpu: 100m
              memory: 60Mi
            limits:
              cpu: 200m
              memory: 120Mi

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-subscription
  labels:
    db: postgres-subscription
spec:
  type: ClusterIP
  selector:
    db: postgres-subscription
  ports:
  - protocol: TCP
    port: 15432
    targetPort: 5432
